name: Deploy Kong changes to PRD

on:
  push:
    branches:
      - main
    paths:
      - PRD/kong/kong.yaml
      - .github/workflows/deploy-kong-PRD.yaml

jobs:
  deploy-kong:
    name: Deploy Kong
    runs-on: self-hosted  # or ubuntu-latest if you are using GitHub-hosted runners

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup deck
        uses: kong/setup-deck@v1
        with:
          deck-version: '1.37.0'
          wrapper: false

      - name: Check DEPLOY_TARGET
        id: check-deploy-target
        run: echo "DEPLOY_TARGET=${{ env.DEPLOY_TARGET }}" >> $GITHUB_ENV

      - name: deck gateway sync to Konnect
        if: env.DEPLOY_TARGET == 'konnect'
        run: |
          deck gateway sync --select-tag platform-repo-managed \
              PRD/kong/kong.yaml \
              --konnect-runtime-group-name KongAir-PRD \
              --konnect-token ${{ secrets.KONNECT_PAT }}

      - name: deck gateway sync locally
        if: env.DEPLOY_TARGET == 'local'
        run: |
          deck sync --select-tag platform-repo-managed \
              PRD/kong/kong.yaml \
              --workspace default \
              --kong-addr http://localhost:8001